# this should be setup for internal testing and deployment as the APK will be tested by the team before being released to the public
# GOOGLE_PLAY_TRACK & track: internal, changes_not_sent_for_review: true, submit_as_draft: false
workflows:
  android-workflow:
    name: Android Workflow
    triggering:
      events:
        - push # Trigger a build on every push event
      branch_patterns:
        - pattern: "*_build" # Match any branch name that ends with _build
        - pattern: "*_droid_fix" # Match any branch name that ends with _droid_fix
    max_build_duration: 120
    environment:
      java: 17
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "us.tke.ninetypercent"
        # GOOGLE_PLAY_TRACK: beta
        GOOGLE_PLAY_TRACK: internal
        KEYSTORE_PATH: "/tmp/keystore.keystore"
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Export TS project
        script: |
          npm run sync:android
      - name: Run Clean
        script: |
          cd dist/android
          chmod +x gradlew
          ./gradlew clean
      - name: Run Build
        script: |
          cd dist/android
          ./gradlew build
      - name: Print Version Number
        script: |
          echo $(($BUILD_NUMBER + 1104))
      - name: Export APK
        script: |
          cd dist/android
          ./gradlew assembleRelease \
            -PversionCode=$(($BUILD_NUMBER + 1104))  \
            -PversionName=1.$(($BUILD_NUMBER + 104))
      - name: Export AAB
        script: |
          cd dist/android
          ./gradlew bundleRelease \
            -PversionCode=$(($BUILD_NUMBER + 1104))  \
            -PversionName=1.$(($BUILD_NUMBER + 104))
      - name: Print APK path
        script: |
          cd dist/android
          echo "android"
          cd app
          echo "app"
          cd build
          echo "build"
          cd outputs
          echo "outputs"
          echo "APK path: $(find . -name '*.aab')"
          echo "APK path: $(find . -name '*.apk')"
      # - name: Push changes to the published branch
      #   script: |
      #     PLATFORM="android"
      #     VERSION="1-$(($BUILD_NUMBER + 104))"
      #     CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      #     TARGET_BRANCH="published"
      #     git checkout $TARGET_BRANCH
      #     git merge --squash $CURRENT_BRANCH
      #     git commit -m "$PLATFORM-$VERSION"
      #     git push origin $TARGET_BRANCH

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - melchiah@tke.us
          - melchiah.mauck@gmail.com
          - chrusionpuroo@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        #track: beta
  ios-workflow:
    name: iOS Workflow
    triggering:
      events:
        - push # Trigger a build on every push event
      branch_patterns:
        - pattern: "*_build" # Match any branch name that ends with _build
        - pattern: "*_ios_fix" # Match any branch name that ends with _build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: TKE
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: us.tke.ninetypercent
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_ID: 0000000000
    scripts:
      # Had to add this because "npm install" was failing. From: https://stackoverflow.com/a/73346047
      - name: Install Canvas Dependencies
        script: |
          brew install pkg-config cairo pango libpng jpeg giflib librsvg
      - name: Install npm dependencies for Ionic Capacitor project
        script: |
          npm install
      - name: Export TS project
        script: |
          npm run sync:ios
      # - name: Cocoapods installation
      #   script: |
      #     cd dist/ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          cd dist/ios/App
          xcode-project use-profiles
      - name: Increment build number
        script: |
          #!/bin/sh
          cd dist/ios/App
          agvtool new-version -all 1.$(($BUILD_NUMBER + 104)).0
          agvtool new-marketing-version 1.$(($BUILD_NUMBER + 104))
      - name: Build ipa for distribution
        script: |
          cd dist/ios/App
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      # - name: Push changes to the published branch
      #   script: |
      #     PLATFORM="ios"
      #     VERSION="1-$(($BUILD_NUMBER + 104))"
      #     CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      #     TARGET_BRANCH="published"
      #     git checkout $TARGET_BRANCH
      #     git merge --squash $CURRENT_BRANCH
      #     git commit -m "$PLATFORM-$VERSION"
      #     git push origin $TARGET_BRANCH

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /ios/App/tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - melchiah@tke.us
          - melchiah.mauck@gmail.com
          # - chrusionpuroo@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: true
        beta_groups:
          - Devs
        # submit_to_app_store: true
        # cancel_previous_submissions: true
        # release_type: AFTER_APPROVAL
        # copyright: 2024 Turn Key Ecosystems LLC
