
import App from "./App.vue";
import AppBar from "./miwi-md/AppBar.vue";
import Body from "./miwi-md/Body.vue";
import Button from "./miwi-md/Button.vue";
import Card from "./miwi-md/Card.vue";
import Column from "./miwi-md/Column.vue";
import DropDown from "./miwi-md/DropDown.vue";
import Field from "./miwi-md/Field.vue";
import Icon from "./miwi-md/Icon.vue";
import NumField from "./miwi-md/NumField.vue";
import Page from "./miwi-md/Page.vue";
import Row from "./miwi-md/Row.vue";
import Slider from "./miwi-md/Slider.vue";
import Stack from "./miwi-md/Stack.vue";
import TabButtons from "./miwi-md/TabButtons.vue";
import TabView from "./miwi-md/TabView.vue";
import Text from "./miwi-md/Text.vue";
import Home from "./views/Home.page.vue";
import Box from "./miwi-md/Box/Box.vue";
import CalculatorsTab from "./views/calculators/CalculatorsTab.vue";
import Client from "./views/clients/Client.page.vue";
import ClientActionBar from "./views/clients/ClientActionBar.vue";
import ClientAndTankSelector from "./views/clients/ClientAndTankSelector.vue";
import ClientEntry from "./views/clients/ClientEntry.vue";
import ClientFields from "./views/clients/ClientFields.vue";
import ClientSearchBar from "./views/clients/ClientSearchBar.vue";
import ClientsTab from "./views/clients/ClientsTab.vue";
import CreateClient from "./views/clients/CreateClient.dialog.vue";
import OutlinedActionButton from "./views/clients/OutlinedActionButton.vue";
import AutoUpdateLoadingScreen from "./views/components/AutoUpdateLoadingScreen.vue";
import DeleteDialog from "./views/components/DeleteDialog.vue";
import DeleteOptionsButton from "./views/components/DeleteOptionsButton.vue";
import Label from "./views/components/Label.vue";
import OfflineWarning from "./views/components/OfflineWarning.vue";
import SerachableDropDown from "./views/components/SerachableDropDown.vue";
import CompletedDeliveryEntry from "./views/deliveries/CompletedDeliveryEntry.vue";
import CompleteDelivery from "./views/deliveries/CompleteDelivery.dialog.vue";
import DeliveriesTab from "./views/deliveries/DeliveriesTab.vue";
import UpcomingDelivery from "./views/deliveries/UpcomingDelivery.dialog.vue";
import UpcomingDeliveryEntry from "./views/deliveries/UpcomingDeliveryEntry.vue";
import CreateFuelType from "./views/settings/CreateFuelType.dialog.vue";
import FuelTypeDropDown from "./views/settings/FuelTypeDropDown.vue";
import FuelTypeEntry from "./views/settings/FuelTypeEntry.vue";
import Settings from "./views/settings/Settings.page.vue";
import SettingsButton from "./views/settings/SettingsButton.vue";
import CreateTank from "./views/tanks/CreateTank.dialog.vue";
import TankEntry from "./views/tanks/TankEntry.vue";
import TankFields from "./views/tanks/TankFields.vue";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    App: typeof App;
AppBar: typeof AppBar;
Body: typeof Body;
Button: typeof Button;
Card: typeof Card;
Column: typeof Column;
DropDown: typeof DropDown;
Field: typeof Field;
Icon: typeof Icon;
NumField: typeof NumField;
Page: typeof Page;
Row: typeof Row;
Slider: typeof Slider;
Stack: typeof Stack;
TabButtons: typeof TabButtons;
TabView: typeof TabView;
Text: typeof Text;
Home: typeof Home;
Box: typeof Box;
CalculatorsTab: typeof CalculatorsTab;
Client: typeof Client;
ClientActionBar: typeof ClientActionBar;
ClientAndTankSelector: typeof ClientAndTankSelector;
ClientEntry: typeof ClientEntry;
ClientFields: typeof ClientFields;
ClientSearchBar: typeof ClientSearchBar;
ClientsTab: typeof ClientsTab;
CreateClient: typeof CreateClient;
OutlinedActionButton: typeof OutlinedActionButton;
AutoUpdateLoadingScreen: typeof AutoUpdateLoadingScreen;
DeleteDialog: typeof DeleteDialog;
DeleteOptionsButton: typeof DeleteOptionsButton;
Label: typeof Label;
OfflineWarning: typeof OfflineWarning;
SerachableDropDown: typeof SerachableDropDown;
CompletedDeliveryEntry: typeof CompletedDeliveryEntry;
CompleteDelivery: typeof CompleteDelivery;
DeliveriesTab: typeof DeliveriesTab;
UpcomingDelivery: typeof UpcomingDelivery;
UpcomingDeliveryEntry: typeof UpcomingDeliveryEntry;
CreateFuelType: typeof CreateFuelType;
FuelTypeDropDown: typeof FuelTypeDropDown;
FuelTypeEntry: typeof FuelTypeEntry;
Settings: typeof Settings;
SettingsButton: typeof SettingsButton;
CreateTank: typeof CreateTank;
TankEntry: typeof TankEntry;
TankFields: typeof TankFields;
  }
}